### ISSUE TITLE
Week 4 exercise - Instructor Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [jordanjones98/indie-project#1]
Nice job implementing the generic dao right away.

Nitpicks: 
- [ ] update javadoc to make it non-user specific:     https://github.com/jordanjones98/indie-project/blob/ac07c892246fa6917e2441c70288d69f0b6b2449/src/main/java/com/houndshobbies/registration/persistence/GenDao.java#L54
- [ ] missing javadoc https://github.com/jordanjones98/indie-project/blob/ac07c892246fa6917e2441c70288d69f0b6b2449/src/test/java/com/houndshobbies/registration/persistence/GenDaoTest.java#L53-L61

**Comment by jordanjones98** [comment]
Updated GenDaoTest with javadoc, and edited GenDao javadoc
